name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: keycloak-twitch-idp
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: keycloak-twitch-idp

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.jar"
